# pre-commit hooks, see https://pre-commit.com
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
    - id: trailing-whitespace
      exclude_types: [markdown]
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-xml
    - id: check-added-large-files
    - id: forbid-new-submodules
    - id: check-symlinks
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: mixed-line-ending
- repo: local
  hooks:
    - id: shellcheck
      name: shellcheck
      entry: shellcheck
      args: [--color=always, --exclude=SC1091]
      language: system
      types: [shell]
